name: loongbao-generator
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.7"
      # run any `bun` or `bunx` command
      - run: cd ./packages/loongbao-generator
      - run: bun install
      - run: bun run build
      - run: pwd && ls
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}